### ISSUE TITLE
My Hope Was Dashed

### ISSUE THREAD

**Issue by sajerestan1** [jlengstorf/code.lengstorf.com#28]
Dear Sir,
I am a beginner at WordPress development. I have no tutor and I learn by reading stuff and watching videos from youtube.

I have been having serious nightmares on using sage and my windows system for some reason could not install yarn.
so I was extremely joyous when I saw the title of your Trellis video on Youtube(Automatic WordPress Deployment + Free SSL: Trellis How-To). I listened to your intro and with hesitation, I download the video.

I was so disappointed when I noticed that you gave no consideration to viewers who have a windows computer. You were only concerned with the Apple computer that you were using.
It would have been a great video because you are an excellent tutor.

I would be very grateful if you can tell me how to get around the Softwares you used for that tutorial that does not work on windows, an example is Homebrew.

Thank you,
Stanley

my email is Sajerestan@gmail.com

**Comment by jlengstorf** [comment]
hey there — that tutorial is several years old at this point, so I unfortunately don't know what the best practices are these days

the Sage team hopefully knows of more up-to-date resources for learning how to use it! good luck!
